// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpeytkxbhtuunwxeuqxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwZXl0a3hiaHR1dW53eGV1cXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Njk4ODQsImV4cCI6MjA2MjI0NTg4NH0.r09JJY0QK3DUIzmAaM9P3Kxxl69LCFe9EENT3zpKhR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);